## Tao User moi
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "Hoang3",
  "password": "St09808098080",
  "firstName": "Eurus",
  "lastName": "Dev",
  "dob": "2004-03-02"
}

### Lay danh sach User (GET)
GET http://localhost:8080/users